apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: grpc-demo-client
        image: grpc-demo-client
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: configmap
        readinessProbe:
          httpGet:
            path: /status
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 2
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /status
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 2
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi