apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: grpc-demo
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: grpc-demo-server
    context: ./static/server/
  - image: grpc-demo-client
    context: ./static/client/
profiles:
- name: local
  build:
    artifacts:
      - image: grpc-demo-server
        context: ./static/server/
        sync:
          infer:
          - 'src/**'
      - image: grpc-demo-client
        context: ./static/client/
        sync:
          infer:
          - 'src/**'
  deploy:
    kubeContext: docker-desktop
    kustomize:
      paths: 
        - ./static/server/manifests/overlays/local
        - ./static/client/manifests/overlays/local
- name: local-dynamic
  build:
    artifacts:
      - image: grpc-demo-server
        context: ./dynamic/server/
        sync:
          infer:
          - 'src/**'
      - image: grpc-demo-client
        context: ./dynamic/client/
        sync:
          infer:
          - 'src/**'
  deploy:
    kubeContext: docker-desktop
    kustomize:
      paths: 
        - ./dynamic/server/manifests/overlays/local
        - ./dynamic/client/manifests/overlays/local
- name: staging
  deploy:
    kubeContext: gke_ms-clients-2018_europe-west1-d_goliath
    kustomize:
      paths: 
        - ./static/server/manifests/overlays/stage
        - ./static/client/manifests/overlays/stage