apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: grpc-demo-server
        image: grpc-demo-server
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        envFrom:
        - configMapRef:
            name: configmap