apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./../../base
namespace: staging
configMapGenerator:
- behavior: merge
  name: configmap
  envs: 
  - config.env
resources:
- ingress.yaml